# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'TestMakeAppointment' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testMakeAppointment' do
    @driver.get('https://katalon-demo-cura.herokuapp.com/')
    @driver.manage.resize_to(1440, 804)
    @driver.find_element(:id, 'btn-make-appointment').click
    @driver.find_element(:id, 'txt-username').click
    @driver.find_element(:id, 'txt-username').send_keys('John Doe')
    @driver.find_element(:id, 'txt-password').send_keys('ThisIsNotAPassword')
    @driver.find_element(:id, 'btn-login').click
    @driver.find_element(:css, '.form-horizontal').click
    @driver.find_element(:css, '.checkbox-inline').click
    @driver.find_element(:id, 'combo_facility').click
    dropdown = @driver.find_element(:id, 'combo_facility')
    dropdown.find_element(:xpath, "//option[. = 'Seoul CURA Healthcare Center']").click
    @driver.find_element(:id, 'txt_visit_date').click
    @driver.find_element(:css, 'tr:nth-child(4) > .day:nth-child(5)').click
    @driver.find_element(:id, 'txt_comment').click
    @driver.find_element(:id, 'txt_comment').send_keys('Test Make Appointment')
    @driver.find_element(:id, 'btn-book-appointment').click
    expect(@driver.find_element(:css, 'h2').text).to eq('Appointment Confirmation')
    @driver.find_element(:css, '.fa-bars').click
    @driver.find_element(:link_text, 'Logout').click
  end
end
